import { default as Console } from '../src/console/index.js';
import { default as Queue } from '../src/datastructures/queue.js';
import { default as Stack } from '../src/datastructures/stack.js';
import { default as Grid } from '../src/datastructures/grid.js';
import { default as ExtendedSet } from '../src/datastructures/set.js';
import { default as Vector } from '../src/datastructures/vector.js';
import { default as Arc } from '../src/graphics/arc.js';
import { default as Circle } from '../src/graphics/circle.js';
import { default as Color } from '../src/graphics/color.js';
import { map, getDistance } from '../src/graphics/graphics-utils.js';
import { default as Group } from '../src/graphics/group.js';
import { default as GraphicsManager } from '../src/graphics/index.js';
import { default as Keyboard } from '../src/graphics/keyboard.js';
import { default as Line } from '../src/graphics/line.js';
import { default as Oval } from '../src/graphics/oval.js';
import { default as Polygon } from '../src/graphics/polygon.js';
import { default as Rectangle } from '../src/graphics/rectangle.js';
import { default as Text } from '../src/graphics/text.js';
import { default as Thing } from '../src/graphics/thing.js';
import { default as WebImage } from '../src/graphics/webimage.js';
import { default as WebVideo } from '../src/graphics/webvideo.js';
import * as Randomizer from '../src/randomizer.js';
import { default as Audio } from '../src/sound/audio.js';
import { default as AudioManager } from '../src/sound/index.js';
import { default as Sound } from '../src/sound/sound.js';

window.Arc = Arc;
window.Audio = Audio;
window.Circle = Circle;
window.Color = Color;
window.Console = Console;
window.Graphics = GraphicsManager;
window.Grid = Grid;
window.Group = Group;
window.Keyboard = Keyboard;
window.Line = Line;
window.Oval = Oval;
window.Polygon = Polygon;
window.Queue = Queue;
window.Randomizer = Randomizer;
window.Rectangle = Rectangle;
window.Set = ExtendedSet;
window.Sound = Sound;
window.Stack = Stack;
window.Text = Text;
window.Thing = Thing;
window.Vector = Vector;
window.WebImage = WebImage;
window.WebVideo = WebVideo;

const GraphicsInstance = new GraphicsManager();
window.__graphics__ = GraphicsInstance;
window.add = GraphicsInstance.add.bind(GraphicsInstance);
window.getWidth = GraphicsInstance.getWidth.bind(GraphicsInstance);
window.getHeight = GraphicsInstance.getHeight.bind(GraphicsInstance);
window.mouseClickMethod = GraphicsInstance.mouseClickMethod.bind(GraphicsInstance);
window.mouseDownMethod = GraphicsInstance.mouseDownMethod.bind(GraphicsInstance);
window.mouseDragMethod = GraphicsInstance.mouseDragMethod.bind(GraphicsInstance);
window.mouseUpMethod = GraphicsInstance.mouseUpMethod.bind(GraphicsInstance);
window.mouseMoveMethod = GraphicsInstance.mouseMoveMethod.bind(GraphicsInstance);
window.stopAllTimers = GraphicsInstance.stopAllTimers.bind(GraphicsInstance);
window.setMainTimer = GraphicsInstance.setMainTimer.bind(GraphicsInstance);
window.stopTimer = GraphicsInstance.stopTimer.bind(GraphicsInstance);
window.setTimer = GraphicsInstance.setTimer.bind(GraphicsInstance);
window.keyDownMethod = GraphicsInstance.keyDownMethod.bind(GraphicsInstance);
window.isKeyPressed = GraphicsInstance.isKeyPressed.bind(GraphicsInstance);
window.removeAll = GraphicsInstance.removeAll.bind(GraphicsInstance);
window.remove = GraphicsInstance.remove.bind(GraphicsInstance);
window.setBackgroundColor = GraphicsInstance.setBackgroundColor.bind(GraphicsInstance);
window.getElementAt = GraphicsInstance.getElementAt.bind(GraphicsInstance);
window.getElementsAt = GraphicsInstance.getElementsAt.bind(GraphicsInstance);
window.setFullscreen = GraphicsInstance.setFullscreen.bind(GraphicsInstance);
window.setSize = GraphicsInstance.setSize.bind(GraphicsInstance);
window.fullReset = GraphicsInstance.fullReset.bind(GraphicsInstance);

const ConsoleInstance = new Console();
window.readLine = ConsoleInstance.readLine.bind(ConsoleInstance);
window.readInt = ConsoleInstance.readInt.bind(ConsoleInstance);
window.println = ConsoleInstance.println.bind(ConsoleInstance);
window.print = ConsoleInstance.print.bind(ConsoleInstance);
window.clear = ConsoleInstance.clear.bind(ConsoleInstance);

const AudioInstance = new AudioManager();
window.audioChangeMethod = AudioInstance.audioChangeMethod.bind(AudioInstance);

window.map = map;
window.getDistance = getDistance;
